version: '3.8'

services:
  booking_api:
    container_name: booking_api
    build:
      context: .
      dockerfile: ./booking-api/BookingRoom.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - booking-sqlserver

  booking-sqlserver:
    container_name: booking-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433"


  angular_app:
    container_name: angular_app
    build:
      context: ./booking-front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - booking_api
      